import { CoffeeBean, TerroirRegion, RoastBatch } from "./types";

export const COFFEE_BEANS: CoffeeBean[] = [
  {
    id: "sumatra_emerald_mandheling",
    name: "蘇門答臘 亞齊 綠寶石曼特寧 G1 TP",
    englishName: "Sumatra Aceh Emerald Mandheling G1 Triple Picked",
    region: "蘇門答臘 亞齊省 (Aceh, Sumatra)",
    processing: "傳統濕剝處理法 (Wet Hulled / Giling Basah)",
    roastLevel: "medium-dark",
    roastLevelText: "中深焙 (Medium-Dark)",
    elevation: "1,500 - 1,700m",
    grade: "G1 Triple Picked (手工三次手選，極低瑕疵)",
    flavorNotes: ["雪松", "乾草草本", "黑巧克力", "煙燻焦糖", "奶油般醇厚"],
    description: "傳統濕剝法造就了極低的酸度、無與倫比的高黏稠度與飽滿甜感。帶著深沉的雪松木質調，與溫潤的亞洲藥草香，尾韻為融化的濃郁黑巧克力。",
    story: "這批綠寶石生豆來自亞齊加約高地的特定小農，在清晨採收完飽滿的鮮紅漿果後，立即進行去皮與半乾燥。隨後以印尼獨特的濕剝技術除去果膠，並在烈日下的高架竹床上細心烘乾，歷經三次手工挑揀，展現最純淨深邃的曼特寧風采。",
    priceHalfPound: 450,
    priceOnePound: 820,
    aroma: 5,
    acidity: 1,
    body: 5,
    sweetness: 4,
    balance: 4,
    image: "/src/assets/images/sumatra_mandheling_1783060496937.jpg",
    inventory: 24,
  },
  {
    id: "sulawesi_toraja_sapan",
    name: "蘇拉威西 托拉雅 薩潘山 G1",
    englishName: "Sulawesi Toraja Mount Sapan G1",
    region: "蘇拉威西 托拉雅 (Mount Sapan, Toraja)",
    processing: "半水洗處理法 (Semi-Washed)",
    roastLevel: "medium",
    roastLevelText: "中焙 (Medium)",
    elevation: "1,800 - 2,100m",
    grade: "Grade 1 (精品頂級莊園豆)",
    flavorNotes: ["葡萄柚", "紅糖", "白豆蔻", "焦糖黑可可", "圓潤滑順"],
    description: "具有蘇拉威西火山高地特有的清新水果風味，微弱而細緻的柑橘酸伴隨著肉桂、白豆蔻的東方辛香，中段焦糖化甜感極佳，質地厚實卻不失乾淨度。",
    story: "薩潘山（Mount Sapan）是托拉雅產區最具盛名的微氣候區，海拔達 2,000 公尺以上。這裡日夜溫差極大，使得咖啡果實能夠極其緩慢地成熟，儲存飽滿的有機酸。這款薩潘山完美融合了高海拔的明亮酸質，與蘇拉威西傳統圓滑、略帶東方香料的迷人餘韻。",
    priceHalfPound: 480,
    priceOnePound: 880,
    aroma: 4,
    acidity: 3,
    body: 4,
    sweetness: 4,
    balance: 5,
    image: "/src/assets/images/sulawesi_toraja_1783060511964.jpg",
    inventory: 15,
  },
  {
    id: "bali_kintamani_volcano",
    name: "巴里島 金塔馬尼 火山高地 日曬",
    englishName: "Bali Kintamani Volcano Highland Natural",
    region: "巴里島 金塔馬尼 (Kintamani, Bali)",
    processing: "精緻全日曬 (Natural / Slow Dry)",
    roastLevel: "light-medium",
    roastLevelText: "淺中焙 (Light-Medium)",
    elevation: "1,300 - 1,500m",
    grade: "Grade 1 Specialty",
    flavorNotes: ["百香果", "野生金桔", "鳳梨甜香", "醇厚黑糖", "發酵威士忌"],
    description: "極具熱帶風情的發酵日曬豆。一入口，百香果與野生柑橘的熱烈酸甜感在口中爆開，伴隨著細緻的黑蜜甜香，最後是略帶威士忌般微醺成熟的酒香韻味。",
    story: "金塔馬尼產區緊鄰巴杜爾活火山（Mount Batur），土壤富含肥沃的火山灰。此地的咖啡農與柑橘果園共生種植，使豆體天生帶有奇妙的柑橘甜香。本批次採用高成本的緩慢日曬乾燥（Slow Dry），讓果肉的果糖充分轉移至豆芯，孕育出飽和度極高的熱帶水果與微醺香氣。",
    priceHalfPound: 500,
    priceOnePound: 920,
    aroma: 5,
    acidity: 4,
    body: 3,
    sweetness: 5,
    balance: 4,
    image: "https://picsum.photos/seed/bali/600/600",
    inventory: 8,
  },
  {
    id: "java_blue_sunda",
    name: "爪哇 巽他 藍眼幽靈 G1",
    englishName: "Java Sunda Blue Ghost G1",
    region: "爪哇島 巽他火山區 (Sunda, West Java)",
    processing: "極致水洗處理法 (Fully Washed)",
    roastLevel: "medium",
    roastLevelText: "中焙 (Medium)",
    elevation: "1,400 - 1,600m",
    grade: "G1 Specialty",
    flavorNotes: ["茉莉花香", "檸檬草", "紅甘蔗甜", "榛果巧克力", "細緻乾淨"],
    description: "非常顛覆傳統印尼豆印象的水洗精品。帶有迷人的白色花香與檸檬草清香，口感清澈乾淨。隨溫度降低，紅甘蔗般的蔗糖甜感與堅果巧克力味逐漸明顯。",
    story: "「巽他」是印尼最早種植咖啡的地區之一，其多霧的微氣候極具神祕感，因而得名「藍眼幽靈」。不同於大眾對印尼豆厚重泥土味的刻板印象，巽他產區近年專注於現代水洗精緻工藝，利用純淨山泉水徹底洗淨黏液，烘托出極致的明亮乾淨度與優雅茶感風味。",
    priceHalfPound: 460,
    priceOnePound: 840,
    aroma: 5,
    acidity: 4,
    body: 3,
    sweetness: 4,
    balance: 5,
    image: "https://picsum.photos/seed/java/600/600",
    inventory: 18,
  },
  {
    id: "flores_bajawa_volcano",
    name: "弗洛勒斯 貝雅瓦 皇家金剛 G1",
    englishName: "Flores Bajawa Ngura Royal G1",
    region: "弗洛勒斯島 貝雅瓦高地 (Bajawa, Flores)",
    processing: "濕剝水洗雙重法 (Wet Hulled & Washed Hybrid)",
    roastLevel: "medium-dark",
    roastLevelText: "中深焙 (Medium-Dark)",
    elevation: "1,550 - 1,800m",
    grade: "G1 Select",
    flavorNotes: ["炒栗子", "楓糖漿", "菸草花香", "香草夾", "焦糖可可"],
    description: "口感扎實而極具包覆感。烘焙至中深焙後，釋放出極為甜美的糖炒栗子與楓糖漿甜度，尾韻略帶淡雅的菸草花香與香草香氣，溫和甘甜、餘韻不絕。",
    story: "弗洛勒斯島（Flores）在拉丁語中意為「花朵之島」。這裡的咖啡生長在多火山的高原地區，常年被朝霧覆蓋。當地的貝雅瓦（Bajawa）原住民保留了對土地的敬畏，採用古老的自然農法。這款豆子呈現的是沉穩厚重的中烘焙，帶著香草和炒榛果的迷人熟甜感，格外適合在冷冬與下午時分細細沖品。",
    priceHalfPound: 420,
    priceOnePound: 780,
    aroma: 4,
    acidity: 2,
    body: 5,
    sweetness: 5,
    balance: 4,
    image: "https://picsum.photos/seed/flores/600/600",
    inventory: 12,
  }
];

export const INDONESIAN_REGIONS: TerroirRegion[] = [
  {
    id: "sumatra",
    name: "蘇門答臘高地 (Sumatra)",
    island: "Sumatra 島",
    elevation: "1,200 - 1,800m",
    soil: "富含鐵、磷質的肥沃半活火山灰土壤",
    processingTradition: "濕剝法 (Giling Basah)",
    flavorProfileSummary: "醇厚飽滿、雪松木質調、東方草本、極低酸度與深邃黑糖甜韻",
    description: "印尼最主要的頂級精品咖啡搖籃。加約高地（Gayo）與多巴湖（Lake Toba）周邊豐沛的雨量與高海拔，配上傳承數百年的濕剝法，讓這裡的咖啡擁有世界最頂級的飽滿黏稠感與迷人的泥土草本微香。",
    aroma: 5,
    acidity: 1,
    body: 5,
    sweetness: 4,
    spiciness: 4
  },
  {
    id: "sulawesi",
    name: "蘇拉威西托拉雅 (Sulawesi Toraja)",
    island: "Sulawesi 島 (舊稱 Celebes)",
    elevation: "1,400 - 2,100m",
    soil: "古老熱帶雨林深層腐殖土、石灰岩沉積與火山砂質",
    processingTradition: "半水洗 (Semi-Washed) 及 水洗 (Washed)",
    flavorProfileSummary: "明亮乾淨的柑橘類酸度、紅糖成熟甜度、圓滑細密質地與淡雅香料餘韻",
    description: "托拉雅（Toraja）高地咖啡被日本及歐洲精品界奉為傳奇。高聳險峻的地勢與極高海拔，使咖啡在純淨的山泉水與溫和日光下孕育，表現出優雅乾淨、如絲綢般柔滑的火山水果甜調。",
    aroma: 4,
    acidity: 3,
    body: 4,
    sweetness: 4,
    spiciness: 3
  },
  {
    id: "bali",
    name: "巴里島金塔馬尼 (Bali Kintamani)",
    island: "Bali 島",
    elevation: "1,200 - 1,500m",
    soil: "巴杜爾活火山肥沃灰燼，富含天然礦物質",
    processingTradition: "精緻日曬 (Natural Slow-Dry) 與 蜜處理 (Honey)",
    flavorProfileSummary: "奔放的百香果與鳳梨甜香、香醇柑橘調、發酵成熟酒香與高甜感",
    description: "金塔馬尼咖啡種植區採用獨特的傳統 Subak Abian 合作農法。咖啡與茂密的柑橘樹、香蕉林交錯共生。充足陽光與火山微氣候，結合細緻日曬乾燥，造就了如水果派對般的絢麗熱帶果香風味。",
    aroma: 5,
    acidity: 4,
    body: 3,
    sweetness: 5,
    spiciness: 2
  },
  {
    id: "java",
    name: "西爪哇巽他 (West Java Sunda)",
    island: "Java 島",
    elevation: "1,300 - 1,600m",
    soil: "西爪哇古老玄武岩火山土壤",
    processingTradition: "精緻水洗 (Fully Washed)",
    flavorProfileSummary: "優雅的茉莉花香、檸檬草清茶感、溫潤蜂蜜與滑順的紅甘蔗蔗糖甜味",
    description: "爪哇是印尼咖啡種植的歷史源頭。巽他（Sunda）地區高山林立，雲霧圍繞。精品微批次在這裡進行完全洗淨的水洗工藝，將傳統爪哇豆粗獷厚實的印象徹底洗脫，留存下優雅清澈的白色花卉與草本甜茶香氣。",
    aroma: 5,
    acidity: 4,
    body: 3,
    sweetness: 4,
    spiciness: 2
  },
  {
    id: "flores",
    name: "弗洛勒斯貝雅瓦 (Flores Bajawa)",
    island: "Flores 島",
    elevation: "1,300 - 1,800m",
    soil: "肥沃鬆軟的火山沉積土質",
    processingTradition: "水洗 (Washed) 及 濕剝法",
    flavorProfileSummary: "堅果栗子甜、濃郁香草氣息、太妃糖焦香、低酸而溫厚綿長",
    description: "貝雅瓦（Bajawa）咖啡生長在弗洛勒斯島的高原活火山盆地。由於高地乾濕季節分明，加上微氣候滋養，咖啡熟甜感特別集中。呈現巧克力、香草與微甜乾菸草的和諧口感，溫和而內斂。",
    aroma: 4,
    acidity: 2,
    body: 5,
    sweetness: 5,
    spiciness: 3
  }
];

export const ROAST_BATCH_LOGS: RoastBatch[] = [
  {
    id: "batch_091",
    batchNumber: "#RB-2026-091",
    beanId: "sumatra_emerald_mandheling",
    beanName: "蘇門答臘 亞齊 綠寶石曼特寧 G1 TP",
    roastDate: "2026-07-02",
    moistureLoss: "14.4%",
    developmentTime: "1m 52s (DTR: 16.5%)",
    roasterName: "Old Yang",
    qualityRating: "卓越",
    notes: "一爆後溫和減率，最大程度保留藥草與雪松木香。脫水良好，排煙順暢。焦糖甜感極為深厚，完美釋放中深焙的奶油體感。"
  },
  {
    id: "batch_090",
    batchNumber: "#RB-2026-090",
    beanId: "bali_kintamani_volcano",
    beanName: "巴里島 金塔馬尼 火山高地 日曬",
    roastDate: "2026-07-02",
    moistureLoss: "12.8%",
    developmentTime: "1m 32s (DTR: 14.1%)",
    roasterName: "Old Yang",
    qualityRating: "優異",
    notes: "採取高火力快速烘焙，提早關風門蓄熱，在一爆密集期前平穩降火。柑橘與百香果的水蜜酸甜高頻感被完美鎖定，伴隨著極致微醺酒香。"
  },
  {
    id: "batch_089",
    batchNumber: "#RB-2026-089",
    beanId: "sulawesi_toraja_sapan",
    beanName: "蘇拉威西 托拉雅 薩潘山 G1",
    roastDate: "2026-07-01",
    moistureLoss: "13.6%",
    developmentTime: "1m 40s (DTR: 15.2%)",
    roasterName: "Old Yang",
    qualityRating: "卓越",
    notes: "脫水期稍微拉長，以引導出薩潘山優雅圓潤的草本花香。中焙出爐時乾淨度極佳，葡萄柚般多汁感與紅糖甜韻極為融洽。"
  },
  {
    id: "batch_088",
    batchNumber: "#RB-2026-088",
    beanId: "java_blue_sunda",
    beanName: "爪哇 巽他 藍眼幽靈 G1",
    roastDate: "2026-06-29",
    moistureLoss: "13.1%",
    developmentTime: "1m 28s (DTR: 13.8%)",
    roasterName: "Old Yang",
    qualityRating: "特優",
    notes: "一爆初即滑行出爐，茉莉花香驚艷。巽他細緻的紅甘蔗蔗糖清甜與檸檬草感非常輕盈，是一次極具藝術感的高海拔水洗豆展現。"
  }
];

export const BREWING_RECIPES = [
  {
    name: "金屬濾網 - 醇厚厚實 (Metal Filter)",
    ratio: 15, // 1:15
    temp: "88°C - 90°C",
    grind: "中等粗細 (砂糖般)",
    steps: "保留較多咖啡油脂 (Coffee Oils)，能將印尼曼特寧與弗洛勒斯豆的奶油稠感、可可甜感放大到極致，入口極致濃郁沉穩。"
  },
  {
    name: "標準手沖 - V60 經典分段 (V60 Dripper)",
    ratio: 15, // 1:15
    temp: "90°C - 92°C",
    grind: "中偏細 (細砂糖)",
    steps: "利用 V60 快速流速，進行三段注水。能激發出巴里島日曬豆的百香果狂野酸甜，或爪哇巽他豆的茉莉花香，乾淨而層次分明。"
  },
  {
    name: "傳統溫潤 - 梯形平底濾杯 (Kalita Wave)",
    ratio: 15, // 1:15
    temp: "89°C - 91°C",
    grind: "中度研磨 (普通砂糖)",
    steps: "利用三孔平底濾杯進行浸潤與慢速萃取。能帶出蘇拉威西托拉雅豆飽滿圓滑的葡萄柚柑橘感與溫和豆蔻辛香，甜感與平衡度均稱頂尖。"
  }
];
